services:
  - type: web
    name: nicornivoras
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: nicolasmedinae06@gmail.com
      - key: ADMIN_PASSWORD
        value: NicoyMati2025!
